export enum RoutePaths {
  ROOT = '/',
  ABOUT = '/about',
  BLOG = '/blog',
  EVENTS = '/events',
  TIMELINE = '/timeline',
  PEOPLE = '/committee',
  CONTACT = '/contact',
  JOIN = '/join',
  LOGIN = '/login',
  SIGN_IN = '/signin',
  MEMBER_LIST = '/member-list',
  DEV = '/dev',
  SW_DEV_WING = '/sw-dev',
}
